name: aur-publish

on:
  push:
    tags:
      - "*"

jobs:
    aur-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
    
        - name: Publish AUR package
          uses: anas-elgarhy/aur-release-action@v4.1
          with:
            package_name: python-mprisgovee
            ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
            github_token: ${{ secrets.GITHUB_TOKEN }}